
<Announcement>:
    orientation: "vertical"
    halign: "center"
    ImageButtonX:
        id: btn
        background_normal: "assets/announcement.png"
        background_down: "assets/announcement.png"
        ratio: 1
        fit_mode: "scale-down"
        size_hint: 0.8, None
        on_press: root.showDetails()
    Label:
        id: timer
        text: "2m00s\n"
        font_size:"10sp"
        opacity: 0
        halign: "left"
        valign: "middle"
        bold: True
